// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.hpw.net2.msg;

public  final class NetMailInit extends
    com.google.protobuf.GeneratedMessage
    implements NetMailInitOrBuilder {
  // Use NetMailInit.newBuilder() to construct.
  private NetMailInit(Builder builder) {
    super(builder);
  }
  private NetMailInit(boolean noInit) {}
  
  private static final NetMailInit defaultInstance;
  public static NetMailInit getDefaultInstance() {
    return defaultInstance;
  }
  
  public NetMailInit getDefaultInstanceForType() {
    return defaultInstance;
  }
  
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hpw.net2.msg.NetData.internal_static_com_hpw_net_msg_NetMailInit_descriptor;
  }
  
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hpw.net2.msg.NetData.internal_static_com_hpw_net_msg_NetMailInit_fieldAccessorTable;
  }
  
  private int bitField0_;
  // required int32 totoalItemCount = 1;
  public static final int TOTOALITEMCOUNT_FIELD_NUMBER = 1;
  private int totoalItemCount_;
  public boolean hasTotoalItemCount() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  public int getTotoalItemCount() {
    return totoalItemCount_;
  }
  
  // required int32 totalPageSize = 2;
  public static final int TOTALPAGESIZE_FIELD_NUMBER = 2;
  private int totalPageSize_;
  public boolean hasTotalPageSize() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  public int getTotalPageSize() {
    return totalPageSize_;
  }
  
  // required int32 currentPageNum = 3;
  public static final int CURRENTPAGENUM_FIELD_NUMBER = 3;
  private int currentPageNum_;
  public boolean hasCurrentPageNum() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  public int getCurrentPageNum() {
    return currentPageNum_;
  }
  
  // required int32 currentPageItemCount = 4;
  public static final int CURRENTPAGEITEMCOUNT_FIELD_NUMBER = 4;
  private int currentPageItemCount_;
  public boolean hasCurrentPageItemCount() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  public int getCurrentPageItemCount() {
    return currentPageItemCount_;
  }
  
  // repeated .com.hpw.net.msg.NetMail mailList = 5;
  public static final int MAILLIST_FIELD_NUMBER = 5;
  private java.util.List<com.hpw.net2.msg.NetMail> mailList_;
  public java.util.List<com.hpw.net2.msg.NetMail> getMailListList() {
    return mailList_;
  }
  public java.util.List<? extends com.hpw.net2.msg.NetMailOrBuilder> 
      getMailListOrBuilderList() {
    return mailList_;
  }
  public int getMailListCount() {
    return mailList_.size();
  }
  public com.hpw.net2.msg.NetMail getMailList(int index) {
    return mailList_.get(index);
  }
  public com.hpw.net2.msg.NetMailOrBuilder getMailListOrBuilder(
      int index) {
    return mailList_.get(index);
  }
  
  // optional int32 senderVipLv = 6;
  public static final int SENDERVIPLV_FIELD_NUMBER = 6;
  private int senderVipLv_;
  public boolean hasSenderVipLv() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  public int getSenderVipLv() {
    return senderVipLv_;
  }
  
  private void initFields() {
    totoalItemCount_ = 0;
    totalPageSize_ = 0;
    currentPageNum_ = 0;
    currentPageItemCount_ = 0;
    mailList_ = java.util.Collections.emptyList();
    senderVipLv_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;
    
    if (!hasTotoalItemCount()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTotalPageSize()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasCurrentPageNum()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasCurrentPageItemCount()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getMailListCount(); i++) {
      if (!getMailList(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }
  
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, totoalItemCount_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, totalPageSize_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, currentPageNum_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, currentPageItemCount_);
    }
    for (int i = 0; i < mailList_.size(); i++) {
      output.writeMessage(5, mailList_.get(i));
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt32(6, senderVipLv_);
    }
    getUnknownFields().writeTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
  
    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, totoalItemCount_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalPageSize_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, currentPageNum_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, currentPageItemCount_);
    }
    for (int i = 0; i < mailList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, mailList_.get(i));
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, senderVipLv_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }
  
  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }
  
  public static com.hpw.net2.msg.NetMailInit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static com.hpw.net2.msg.NetMailInit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static com.hpw.net2.msg.NetMailInit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static com.hpw.net2.msg.NetMailInit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static com.hpw.net2.msg.NetMailInit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static com.hpw.net2.msg.NetMailInit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  public static com.hpw.net2.msg.NetMailInit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static com.hpw.net2.msg.NetMailInit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static com.hpw.net2.msg.NetMailInit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static com.hpw.net2.msg.NetMailInit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  
  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.hpw.net2.msg.NetMailInit prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }
  
  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.hpw.net2.msg.NetMailInitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hpw.net2.msg.NetData.internal_static_com_hpw_net_msg_NetMailInit_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hpw.net2.msg.NetData.internal_static_com_hpw_net_msg_NetMailInit_fieldAccessorTable;
    }
    
    // Construct using com.hpw.net2.msg.NetMailInit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }
    
    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getMailListFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }
    
    public Builder clear() {
      super.clear();
      totoalItemCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      totalPageSize_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      currentPageNum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      currentPageItemCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (mailListBuilder_ == null) {
        mailList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        mailListBuilder_.clear();
      }
      senderVipLv_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    
    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }
    
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hpw.net2.msg.NetMailInit.getDescriptor();
    }
    
    public com.hpw.net2.msg.NetMailInit getDefaultInstanceForType() {
      return com.hpw.net2.msg.NetMailInit.getDefaultInstance();
    }
    
    public com.hpw.net2.msg.NetMailInit build() {
      com.hpw.net2.msg.NetMailInit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }
    
    private com.hpw.net2.msg.NetMailInit buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
      com.hpw.net2.msg.NetMailInit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(
          result).asInvalidProtocolBufferException();
      }
      return result;
    }
    
    public com.hpw.net2.msg.NetMailInit buildPartial() {
      com.hpw.net2.msg.NetMailInit result = new com.hpw.net2.msg.NetMailInit(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.totoalItemCount_ = totoalItemCount_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.totalPageSize_ = totalPageSize_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.currentPageNum_ = currentPageNum_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.currentPageItemCount_ = currentPageItemCount_;
      if (mailListBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          mailList_ = java.util.Collections.unmodifiableList(mailList_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.mailList_ = mailList_;
      } else {
        result.mailList_ = mailListBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000010;
      }
      result.senderVipLv_ = senderVipLv_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }
    
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hpw.net2.msg.NetMailInit) {
        return mergeFrom((com.hpw.net2.msg.NetMailInit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }
    
    public Builder mergeFrom(com.hpw.net2.msg.NetMailInit other) {
      if (other == com.hpw.net2.msg.NetMailInit.getDefaultInstance()) return this;
      if (other.hasTotoalItemCount()) {
        setTotoalItemCount(other.getTotoalItemCount());
      }
      if (other.hasTotalPageSize()) {
        setTotalPageSize(other.getTotalPageSize());
      }
      if (other.hasCurrentPageNum()) {
        setCurrentPageNum(other.getCurrentPageNum());
      }
      if (other.hasCurrentPageItemCount()) {
        setCurrentPageItemCount(other.getCurrentPageItemCount());
      }
      if (mailListBuilder_ == null) {
        if (!other.mailList_.isEmpty()) {
          if (mailList_.isEmpty()) {
            mailList_ = other.mailList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureMailListIsMutable();
            mailList_.addAll(other.mailList_);
          }
          onChanged();
        }
      } else {
        if (!other.mailList_.isEmpty()) {
          if (mailListBuilder_.isEmpty()) {
            mailListBuilder_.dispose();
            mailListBuilder_ = null;
            mailList_ = other.mailList_;
            bitField0_ = (bitField0_ & ~0x00000010);
            mailListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMailListFieldBuilder() : null;
          } else {
            mailListBuilder_.addAllMessages(other.mailList_);
          }
        }
      }
      if (other.hasSenderVipLv()) {
        setSenderVipLv(other.getSenderVipLv());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }
    
    public final boolean isInitialized() {
      if (!hasTotoalItemCount()) {
        
        return false;
      }
      if (!hasTotalPageSize()) {
        
        return false;
      }
      if (!hasCurrentPageNum()) {
        
        return false;
      }
      if (!hasCurrentPageItemCount()) {
        
        return false;
      }
      for (int i = 0; i < getMailListCount(); i++) {
        if (!getMailList(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }
    
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder(
          this.getUnknownFields());
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            onChanged();
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            totoalItemCount_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            totalPageSize_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            currentPageNum_ = input.readInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            currentPageItemCount_ = input.readInt32();
            break;
          }
          case 42: {
            com.hpw.net2.msg.NetMail.Builder subBuilder = com.hpw.net2.msg.NetMail.newBuilder();
            input.readMessage(subBuilder, extensionRegistry);
            addMailList(subBuilder.buildPartial());
            break;
          }
          case 48: {
            bitField0_ |= 0x00000020;
            senderVipLv_ = input.readInt32();
            break;
          }
        }
      }
    }
    
    private int bitField0_;
    
    // required int32 totoalItemCount = 1;
    private int totoalItemCount_ ;
    public boolean hasTotoalItemCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTotoalItemCount() {
      return totoalItemCount_;
    }
    public Builder setTotoalItemCount(int value) {
      bitField0_ |= 0x00000001;
      totoalItemCount_ = value;
      onChanged();
      return this;
    }
    public Builder clearTotoalItemCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      totoalItemCount_ = 0;
      onChanged();
      return this;
    }
    
    // required int32 totalPageSize = 2;
    private int totalPageSize_ ;
    public boolean hasTotalPageSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTotalPageSize() {
      return totalPageSize_;
    }
    public Builder setTotalPageSize(int value) {
      bitField0_ |= 0x00000002;
      totalPageSize_ = value;
      onChanged();
      return this;
    }
    public Builder clearTotalPageSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalPageSize_ = 0;
      onChanged();
      return this;
    }
    
    // required int32 currentPageNum = 3;
    private int currentPageNum_ ;
    public boolean hasCurrentPageNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getCurrentPageNum() {
      return currentPageNum_;
    }
    public Builder setCurrentPageNum(int value) {
      bitField0_ |= 0x00000004;
      currentPageNum_ = value;
      onChanged();
      return this;
    }
    public Builder clearCurrentPageNum() {
      bitField0_ = (bitField0_ & ~0x00000004);
      currentPageNum_ = 0;
      onChanged();
      return this;
    }
    
    // required int32 currentPageItemCount = 4;
    private int currentPageItemCount_ ;
    public boolean hasCurrentPageItemCount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getCurrentPageItemCount() {
      return currentPageItemCount_;
    }
    public Builder setCurrentPageItemCount(int value) {
      bitField0_ |= 0x00000008;
      currentPageItemCount_ = value;
      onChanged();
      return this;
    }
    public Builder clearCurrentPageItemCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      currentPageItemCount_ = 0;
      onChanged();
      return this;
    }
    
    // repeated .com.hpw.net.msg.NetMail mailList = 5;
    private java.util.List<com.hpw.net2.msg.NetMail> mailList_ =
      java.util.Collections.emptyList();
    private void ensureMailListIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        mailList_ = new java.util.ArrayList<com.hpw.net2.msg.NetMail>(mailList_);
        bitField0_ |= 0x00000010;
       }
    }
    
    private com.google.protobuf.RepeatedFieldBuilder<
        com.hpw.net2.msg.NetMail, com.hpw.net2.msg.NetMail.Builder, com.hpw.net2.msg.NetMailOrBuilder> mailListBuilder_;
    
    public java.util.List<com.hpw.net2.msg.NetMail> getMailListList() {
      if (mailListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mailList_);
      } else {
        return mailListBuilder_.getMessageList();
      }
    }
    public int getMailListCount() {
      if (mailListBuilder_ == null) {
        return mailList_.size();
      } else {
        return mailListBuilder_.getCount();
      }
    }
    public com.hpw.net2.msg.NetMail getMailList(int index) {
      if (mailListBuilder_ == null) {
        return mailList_.get(index);
      } else {
        return mailListBuilder_.getMessage(index);
      }
    }
    public Builder setMailList(
        int index, com.hpw.net2.msg.NetMail value) {
      if (mailListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMailListIsMutable();
        mailList_.set(index, value);
        onChanged();
      } else {
        mailListBuilder_.setMessage(index, value);
      }
      return this;
    }
    public Builder setMailList(
        int index, com.hpw.net2.msg.NetMail.Builder builderForValue) {
      if (mailListBuilder_ == null) {
        ensureMailListIsMutable();
        mailList_.set(index, builderForValue.build());
        onChanged();
      } else {
        mailListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    public Builder addMailList(com.hpw.net2.msg.NetMail value) {
      if (mailListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMailListIsMutable();
        mailList_.add(value);
        onChanged();
      } else {
        mailListBuilder_.addMessage(value);
      }
      return this;
    }
    public Builder addMailList(
        int index, com.hpw.net2.msg.NetMail value) {
      if (mailListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMailListIsMutable();
        mailList_.add(index, value);
        onChanged();
      } else {
        mailListBuilder_.addMessage(index, value);
      }
      return this;
    }
    public Builder addMailList(
        com.hpw.net2.msg.NetMail.Builder builderForValue) {
      if (mailListBuilder_ == null) {
        ensureMailListIsMutable();
        mailList_.add(builderForValue.build());
        onChanged();
      } else {
        mailListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    public Builder addMailList(
        int index, com.hpw.net2.msg.NetMail.Builder builderForValue) {
      if (mailListBuilder_ == null) {
        ensureMailListIsMutable();
        mailList_.add(index, builderForValue.build());
        onChanged();
      } else {
        mailListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    public Builder addAllMailList(
        java.lang.Iterable<? extends com.hpw.net2.msg.NetMail> values) {
      if (mailListBuilder_ == null) {
        ensureMailListIsMutable();
        super.addAll(values, mailList_);
        onChanged();
      } else {
        mailListBuilder_.addAllMessages(values);
      }
      return this;
    }
    public Builder clearMailList() {
      if (mailListBuilder_ == null) {
        mailList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        mailListBuilder_.clear();
      }
      return this;
    }
    public Builder removeMailList(int index) {
      if (mailListBuilder_ == null) {
        ensureMailListIsMutable();
        mailList_.remove(index);
        onChanged();
      } else {
        mailListBuilder_.remove(index);
      }
      return this;
    }
    public com.hpw.net2.msg.NetMail.Builder getMailListBuilder(
        int index) {
      return getMailListFieldBuilder().getBuilder(index);
    }
    public com.hpw.net2.msg.NetMailOrBuilder getMailListOrBuilder(
        int index) {
      if (mailListBuilder_ == null) {
        return mailList_.get(index);  } else {
        return mailListBuilder_.getMessageOrBuilder(index);
      }
    }
    public java.util.List<? extends com.hpw.net2.msg.NetMailOrBuilder> 
         getMailListOrBuilderList() {
      if (mailListBuilder_ != null) {
        return mailListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mailList_);
      }
    }
    public com.hpw.net2.msg.NetMail.Builder addMailListBuilder() {
      return getMailListFieldBuilder().addBuilder(
          com.hpw.net2.msg.NetMail.getDefaultInstance());
    }
    public com.hpw.net2.msg.NetMail.Builder addMailListBuilder(
        int index) {
      return getMailListFieldBuilder().addBuilder(
          index, com.hpw.net2.msg.NetMail.getDefaultInstance());
    }
    public java.util.List<com.hpw.net2.msg.NetMail.Builder> 
         getMailListBuilderList() {
      return getMailListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.hpw.net2.msg.NetMail, com.hpw.net2.msg.NetMail.Builder, com.hpw.net2.msg.NetMailOrBuilder> 
        getMailListFieldBuilder() {
      if (mailListBuilder_ == null) {
        mailListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.hpw.net2.msg.NetMail, com.hpw.net2.msg.NetMail.Builder, com.hpw.net2.msg.NetMailOrBuilder>(
                mailList_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        mailList_ = null;
      }
      return mailListBuilder_;
    }
    
    // optional int32 senderVipLv = 6;
    private int senderVipLv_ ;
    public boolean hasSenderVipLv() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getSenderVipLv() {
      return senderVipLv_;
    }
    public Builder setSenderVipLv(int value) {
      bitField0_ |= 0x00000020;
      senderVipLv_ = value;
      onChanged();
      return this;
    }
    public Builder clearSenderVipLv() {
      bitField0_ = (bitField0_ & ~0x00000020);
      senderVipLv_ = 0;
      onChanged();
      return this;
    }
    
    // @@protoc_insertion_point(builder_scope:com.hpw.net.msg.NetMailInit)
  }
  
  static {
    defaultInstance = new NetMailInit(true);
    defaultInstance.initFields();
  }
  
  // @@protoc_insertion_point(class_scope:com.hpw.net.msg.NetMailInit)
}

