// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.hpw.net2.msg;

public interface NetMailInitOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required int32 totoalItemCount = 1;
  boolean hasTotoalItemCount();
  int getTotoalItemCount();
  
  // required int32 totalPageSize = 2;
  boolean hasTotalPageSize();
  int getTotalPageSize();
  
  // required int32 currentPageNum = 3;
  boolean hasCurrentPageNum();
  int getCurrentPageNum();
  
  // required int32 currentPageItemCount = 4;
  boolean hasCurrentPageItemCount();
  int getCurrentPageItemCount();
  
  // repeated .com.hpw.net.msg.NetMail mailList = 5;
  java.util.List<com.hpw.net2.msg.NetMail> 
      getMailListList();
  com.hpw.net2.msg.NetMail getMailList(int index);
  int getMailListCount();
  java.util.List<? extends com.hpw.net2.msg.NetMailOrBuilder> 
      getMailListOrBuilderList();
  com.hpw.net2.msg.NetMailOrBuilder getMailListOrBuilder(
      int index);
  
  // optional int32 senderVipLv = 6;
  boolean hasSenderVipLv();
  int getSenderVipLv();
}
