spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    password:
    # Redis 数据库号，默认为 0 。
    database: 0
    # Redis 连接超时时间，默认单位：毫秒。
    timeout: 1S
    # 可以用 lettuce/jedis，如果要用后者需要排除lettuce依赖
    lettuce:
      pool:
        # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-active: 16
        # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 10
        # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        min-idle: 1
        # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。
        max-wait: 1000